### ISSUE TITLE
Dont installs into Contao 4.12.5 

### ISSUE THREAD

**Issue by Joam55** [heimrichhannot/contao-banner_plus#4]
Problem 1
    - heimrichhannot/contao-banner-plus-bundle[1.1.1, ..., 1.1.4] require bugbuster/banner 3.5.* -> satisfiable by bugbuster/banner[3.5.0, ..., 3.5.5].
    - heimrichhannot/contao-banner-plus-bundle 1.1.0 requires bugbuster/banner >=3.5,<3.6-dev -> satisfiable by bugbuster/banner[3.5.0, ..., 3.5.5].
    - bugbuster/banner[3.5.4, ..., 3.5.5] require contao/core >=3.5.1,<4 -> satisfiable by contao/core[3.5.1, ..., 3.5.40].
    - bugbuster/banner[3.5.0, ..., 3.5.3] require contao/core >=3.4,<4 -> satisfiable by contao/core[3.4.0, ..., 3.5.40].
    - contao/core[3.4.0, ..., 3.5.40] require contao-community-alliance/composer-plugin ~2.0 -> satisfiable by contao-community-alliance/composer-plugin[2.0.0, ..., 2.4.3].
    - contao-community-alliance/composer-plugin[2.0.0, ..., 2.3.3] require composer-plugin-api 1.0.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - contao-community-alliance/composer-plugin[2.3.4, ..., 2.4.3] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - Root composer.json requires heimrichhannot/contao-banner-plus-bundle ^1.1 -> satisfiable by heimrichhannot/contao-banner-plus-bundle[1.1.0, ..., 1.1.4].

Danke für Support!

dtptiger

**Comment by koertho** [comment]
Hallo, für Contao-4-Support musst du die 2.0-beta-branch verwenden. Allerdings haben wir das Bundle nicht oft im Einsatz, daher ist es nicht sonderlich gut gewartet.

**Comment by Joam55** [comment]
Hallo, 

leider nein, auch mit der  2.0-beta-branch und mit Contao 4.9.24 läuft die site nicht:

`[2022-01-31 13:12:20] request.INFO: Matched route "contao_backend_login". {"route":"contao_backend_login","route_parameters":{"_route":"contao_backend_login","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::loginAction"},"request_uri":"https://test1.mywebsite.de/contao/login?_hash=Apd47nW1YOhV7qSuEvbgV7nwiZf%2BMH011gasy4xG3Tw%3D&redirect=https%3A%2F%2Ftest1.mywebsite.de%2Fcontao","method":"GET"} []
[2022-01-31 13:12:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2022-01-31 13:12:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "HeimrichHannot\UtilsBundle\Container\ContainerUtil"." at /var/customers/webs/mywebsite/test1.mywebsite.de/vendor/symfony/dependency-injection/Container.php line 289 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"HeimrichHannot\\UtilsBundle\\Container\\ContainerUtil\". at /var/customers/webs/mywebsite/test1.mywebsite.de/vendor/symfony/dependency-injection/Container.php:289)"} []
` 
Dann vielleicht irgendwann. Danke für Eure Mühe!
Gruß dtptiger

**Comment by koertho** [comment]
Das sieht so aus wie eine veraltete Utils-Bundle version, update mal heimrichhannot/contao-utils-bundle

**Comment by Joam55** [comment]
Kein Erfolg:
composer update heimrichhannot/contao-banner-plus-bundle contao/conflicts
... exit

Egal ob im Manager  "2.0.0-beta6" steht, oder "^2.0.0-beta6"

**Comment by koertho** [comment]
Sorry, deine Nachricht verstehe ich nicht. Ich vermute, du hast eine alte Version des utils-bundle installiert. Das banner_plus hast du doch schon geupdated, wenn ich deinen vorherigen Kommentar richtig deute. Ansonste immer bitte die komplette Fehlermeldung posten.

**Comment by Joam55** [comment]
Ok, ja, ich versuche das mit dem Manager:

$ /usr/bin/php7.4 -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /var/customers/webs/my-site/web/contao-manager.phar.php composer require heimrichhannot/contao-banner-plus-bundle --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^1.1 for heimrichhannot/contao-banner-plus-bundle
/var/customers/webs/my-site/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


$ /usr/bin/php7.4 -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /var/customers/webs/my-site/web/contao-manager.phar.php composer update heimrichhannot/contao-banner-plus-bundle contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader

Loading composer repositories with package information
Dependency "heimrichhannot/contao-mediaquery" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/calendar-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/comments-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/faq-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/listing-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/news-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "contao/newsletter-bundle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - heimrichhannot/contao-banner-plus-bundle[1.1.1, ..., 1.1.4] require bugbuster/banner 3.5.* -> satisfiable by bugbuster/banner[3.5.0, ..., 3.5.5].
    - heimrichhannot/contao-banner-plus-bundle 1.1.0 requires bugbuster/banner >=3.5,<3.6-dev -> satisfiable by bugbuster/banner[3.5.0, ..., 3.5.5].
    - bugbuster/banner[3.5.4, ..., 3.5.5] require contao/core >=3.5.1,<4 -> satisfiable by contao/core[3.5.1, ..., 3.5.40].
    - bugbuster/banner[3.5.0, ..., 3.5.3] require contao/core >=3.4,<4 -> satisfiable by contao/core[3.4.0, ..., 3.5.40].
    - contao/core[2.11.0, ..., 2.11.17, 3.0.0, ..., 3.5.40] cannot be installed as that would require removing contao/calendar-bundle[4.9.24]. contao/core replaces contao/calendar-bundle and thus cannot coexist with it.
    - contao/calendar-bundle is locked to version 4.9.24 and an update of this package was not requested.
    - Root composer.json requires heimrichhannot/contao-banner-plus-bundle ^1.1 -> satisfiable by heimrichhannot/contao-banner-plus-bundle[1.1.0, ..., 1.1.4].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

# Process terminated with exit code 2
# Result: Misuse of shell builtins
![screenshot_22](https://user-images.githubusercontent.com/108203/151829429-40f66e5f-e0ad-4fd5-b45c-374cda130136.png)

**Comment by koertho** [comment]
Dein Eintrag in der composer.json müsste so aussehen: `"heimrichhannot/contao-banner-plus-bundle": "^2.0-beta"`

**Comment by Joam55** [comment]
Leider noch nicht ...
Das steht in der composer.json

{
    "type": "project",
    "require": {
        "contao/calendar-bundle": "4.9.*",
        "contao/comments-bundle": "4.9.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.9.*",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "contao/newsletter-bundle": "4.9.*",
        "heimrichhannot/contao-mediaquery": "^1.1",
        "heimrichhannot/contao-banner-plus-bundle": "^2.0-beta"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

**Comment by Joam55** [comment]
Das ist der consolen output:

$ /usr/bin/php7.4 -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /var/customers/webs/vonflatow/test1.vonflatow.de/web/contao-manager.phar.php composer update heimrichhannot/contao-banner-plus-bundle contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader

Loading composer repositories with package information
Dependency "heimrichhannot/contao-mediaquery" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Lock file operations: 5 installs, 0 updates, 0 removals
  - Locking bugbuster/browscap-lite (1.1.2)
  - Locking bugbuster/contao-banner-bundle (1.0.10.4)
  - Locking bugbuster/contao-botdetection-bundle (1.7.1)
  - Locking heimrichhannot/contao-banner-plus-bundle (2.0.0-beta6)
  - Locking jaybizzle/crawler-detect (v1.2.110)
Writing lock file
Installing dependencies from lock file
Package operations: 5 installs, 0 updates, 0 removals
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' may remediate them.
  - Installing jaybizzle/crawler-detect (v1.2.110): Extracting archive
  - Installing bugbuster/browscap-lite (1.1.2): Extracting archive
  - Installing bugbuster/contao-botdetection-bundle (1.7.1): Extracting archive
  - Installing bugbuster/contao-banner-bundle (1.0.10.4): Extracting archive
  - Installing heimrichhannot/contao-banner-plus-bundle (2.0.0-beta6): Extracting archive
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
87 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Added the web/app.php file.
Added the web/index.php file.
Added the web/preview.php file.

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

18:49:49 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod". Message: "You have requested a non-existent service "HeimrichHannot\UtilsBundle\Container\ContainerUtil"." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException { …},"command" => "cache:warmup --env=prod","message" => "You have requested a non-existent service "HeimrichHannot\UtilsBundle\Container\ContainerUtil"."]

In Container.php line 289:
                                                                               
  You have requested a non-existent service "HeimrichHannot\UtilsBundle\Conta  
  iner\ContainerUtil".                                                         
                                                                               

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] 

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

In ScriptHandler.php line 89:
                                                                               
  An error occurred while executing the "cache:warmup" command: 18:49:49 CRIT  
  ICAL  [console] Error thrown while running command "cache:warmup --env=prod  
  ". Message: "You have requested a non-existent service "HeimrichHannot\Util  
  sBundle\Container\ContainerUtil"." ["exception" => Symfony\Component\Depend  
  encyInjection\Exception\ServiceNotFoundException { …},"command" => "cache:w  
  armup --env=prod","message" => "You have requested a non-existent service "  
  HeimrichHannot\UtilsBundle\Container\ContainerUtil"."]                       
                                                                               
  In Container.php line 289:                                                   
                                                                               
                                                                               
    You have requested a non-existent service "HeimrichHannot\UtilsBundle\Con  
  ta                                                                           
    iner\ContainerUtil".                                                       
                                                                               
                                                                               
                                                                               
                                                                               
  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--  
  verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en  
  v ENV] [--]                                                         
                                                                               

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [...]


# Process terminated with exit code 1
# Result: General error

**Comment by Joam55** [comment]
So schauts im Manager aus:

![screenshot_23](https://user-images.githubusercontent.com/108203/151847131-01313dd1-7cae-41cd-96c9-d3175a125b72.png)

**Comment by Joam55** [comment]
Das installtool wirft diese Fehlermeldung aus:

[2022-01-31 18:56:46] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"https://.mysite.de/contao/install","method":"GET"} []
[2022-01-31 18:56:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "HeimrichHannot\UtilsBundle\Container\ContainerUtil"." at /var/customers/webs/mysite/vendor/symfony/dependency-injection/Container.php line 289 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"HeimrichHannot\\UtilsBundle\\Container\\ContainerUtil\". at /var/customers/webs/mysite/vendor/symfony/dependency-injection/Container.php:289)"} []

**Comment by koertho** [comment]
Welche Version des Utils-Bundle ist installiert?

**Comment by Joam55** [comment]
Das steht im changelog.md:
(die erten paar Zeilen)

# Change Log
All notable changes to this project will be documented in this file.

## [2.0.0-beta6] - 2021-09-28
- fixed banner_start and banner_end to be displayed correctly in backend

## [2.0.0-beta5] - 2021-07-27
- fixed backend js bundle name

## [2.0.0-beta4] - 2021-07-27
- added new banner type HTML(#1)
- added encore configuration
- added backend js

## [2.0.0-beta3] - 2020-02-18
- fixed another dca install error

**Comment by koertho** [comment]
Wie bereits mehrfach geschrieben rede ich vom Utils-Bundle, nicht von Banner_Plus ([heimrichhannot/contao-utils-bundle](https://github.com/heimrichhannot/contao-utils-bundle))

**Comment by Joam55** [comment]
OK 🙄

**Comment by Joam55** [comment]
Danke!
Jetzt hat der install geklappt. 
Es braucht also diese Bundles:

        "heimrichhannot/contao-mediaquery": "^1.1",
         "heimrichhannot/contao-utils-bundle": "^2.2",

um dieses zum install zu bringen:

         "heimrichhannot/contao-banner-plus-bundle": "^2.0-beta"

In den Abhängigkeiten vom contao-banner-plus-bundle steht nur:

heimrichhannot/contao-mediaquery^1.1

Ich glaube wenn in den Abhängigkeiten auch heimrichhannot/contao-utils-bundle stehen würde wäre das von Vorteil.

Vielen Dank für deine Hilfe!
Gruß dtptiger

**Comment by koertho** [comment]
@Joam55 Ui, ja, das sollte natürlich eine Abhängigkeit sein. Danke für den Hinweiß!

**Comment by Joam55** [comment]
Wunderbar :)
